name: tutor_link_app
description: A bilingual mobile platform connecting students and tutors

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  video_player: ^2.8.1
  flutter_rating_bar: ^4.0.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true